Mon 27 Nov 2017 18:50:53 TwitterError __init__ 16316 Thread-1 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:53 rest_api get_users_lookup 16316 Thread-1 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:55 TwitterError __init__ 18672 Thread-3 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:55 TwitterError __init__ 18300 Thread-5 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:55 TwitterError __init__ 6504 Thread-7 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:55 rest_api get_users_lookup 18672 Thread-3 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:55 rest_api get_users_lookup 18300 Thread-5 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:55 rest_api get_users_lookup 6504 Thread-7 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 TwitterError __init__ 18736 Thread-2 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 rest_api get_users_lookup 18736 Thread-2 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 TwitterError __init__ 13112 Thread-8 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 rest_api get_users_lookup 13112 Thread-8 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 TwitterError __init__ 7400 Thread-6 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 TwitterError __init__ 15576 Thread-4 [line:22] WARNING 400 statuses/filter text HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 rest_api get_users_lookup 7400 Thread-6 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Mon 27 Nov 2017 18:50:57 rest_api get_users_lookup 15576 Thread-4 [line:120] ERROR HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/lookup.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
